name: CI

on:
  push:
    branches:
      - develop
      - master
  pull_request:

# Ensure only one occurrence per branch or PR is running.
concurrency:
  group: ci-code-check-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  # ---------- Initialise------------------------------------------------------
  init:
    name: Initialise
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup & Cache
        uses: ./.github/actions/setup-and-cache

  # # ---------- Build ----------------------------------------------------------
  # build-web:
  #   name: Build Recitry Web
  #   needs: init
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Load Cache
  #       uses: ./.github/actions/setup-and-cache

  #     - run: npm run type-check
  #     - run: npm run build:web
  # build-api:
  #   name: Build Recitry API
  #   needs: init
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Load Cache
  #       uses: ./.github/actions/setup-and-cache

  #     - run: npm run build:api

  # ---------- CI -------------------------------------------------------------
  build:
    name: Build
    needs: init
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Load Cache
        uses: ./.github/actions/setup-and-cache

      - name: Run build check
        run: npm run build:all

  type-check:
    name: Type checking
    needs: init
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Load Cache
        uses: ./.github/actions/setup-and-cache

      - name: Run type check
        run: npm run type-check:all

  test:
    name: Test
    needs: init
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Load Cache
        uses: ./.github/actions/setup-and-cache

      - name: Run test
        run: npm run test:all
